apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # Class
  storageClassName: local-storage
  # Selector
  selector:
    matchLabels:
      type: gitea-pv