---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'kafka-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['kafka-exporter-service.kafka.svc.cluster.local:9308']
      - job_name: 'kafka-jmx'
        metrics_path: /
        static_configs:
          - targets: ['kafka-service.kafka.svc.cluster.local:9999']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus
        args: 
          - '--config.file=/etc/prometheus/prometheus.yml'
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-yml
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-yml
        configMap:
          name: prometheus-config
          items:
          - key: prometheus.yml
            path: prometheus.yml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: prometheus-port
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 9090
  selector:
    app: prometheus