apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: test-namespace
  labels:
    k8s-app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jenkins
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-alpine
        imagePullPolicy: IfNotPresent
        env:
          - name: JENKINS_ARGS
            value: "--prefix=/jenkins"
          - name: JENKINS_OPTS
            value: "--prefix=/jenkins"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 50000
          name: agent
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
      nodeSelector:
        nodetype: worker