apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
  namespace: kafka
spec:
  ports:
  - name: kafka-port
    protocol: TCP
    port: 9092
    targetPort: 9092
  selector:
    app: kafka