kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kafka
  name: kafka-deployment
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
      - name: kafka
        # image: wurstmeister/kafka
        image: cathay-kafka:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service.kafka.svc.cluster.local
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service.kafka.svc.cluster.local:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_OPTS
          value: "-javaagent:${KAFKA_HOME}/prometheus/jmx_prometheus_javaagent-0.13.0.jar=9999:${KAFKA_HOME}/prometheus/kafka-2_0_0.yml"