apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-exporter
  name: kafka-exporter-service
  namespace: kafka
spec:
  ports:
  - name: kafka-exporter-port
    protocol: TCP
    port: 9308
    targetPort: 9308
  selector:
    app: kafka-exporter