DROP TABLE IF EXISTS `dtaga001_prod_defi`;
CREATE TABLE IF NOT EXISTS `dtaga001_prod_defi` (
  `PROD_ID` VARCHAR(3) NOT NULL COMMENT '商品代號',
  `PROD_NAME` VARCHAR(60) COMMENT '商品中文全名'
) ENGINE=InnoDB DEFAULT CHARACTER=utf8 COMMENT='基本資料定義檔';
ALTER TABLE `dtaga001_prod_defi`
  ADD CONSTRAINT `DTAGA001_PK` PRIMARY KEY 
    (`PROD_ID`);