DROP TABLE IF EXISTS `DTAGA001_PROD_DEFI`;
CREATE TABLE IF NOT EXISTS `DTAGA001_PROD_DEFI` (
  `PROD_ID` VARCHAR(3) NOT NULL,
  `PROD_NAME` VARCHAR(60),
  PRIMARY KEY (`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;