apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # Class
  storageClassName: my-local-storage
  # Selector
  selector:
    matchLabels:
      type: local