apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "my-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi