apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stateful
  namespace: test-namespace
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 4
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11-alpine
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      nodeSelector:
        nodetype: db
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: my-nfs-storage
      resources:
        requests:
          storage: 3Gi