apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfrog-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # Class
  storageClassName: local-storage
  # Selector
  selector:
    matchLabels:
      type: jfrog-pv