apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycat-deployment
  namespace: test-namespace
  labels:
    app: mycat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycat
  template:
    metadata:
      labels:
        app: mycat
    spec:
      containers:
      - name: mycat
        image: hub.cathay/mycat:0.0.1-release
        ports:
        - containerPort: 8066
          name: mycat
        volumeMounts:
        - mountPath: /mycat/logs
          name: mycat-data
          subPath: logs
        - name: mycat-rule-xml
          mountPath: /mycat/conf/rule.xml
          subPath: rule.xml
        - name: mycat-schema-xml
          mountPath: /mycat/conf/schema.xml
          subPath: schema.xml
        - name: mycat-server-xml
          mountPath: /mycat/conf/server.xml
          subPath: server.xml
      volumes:
      - name: mycat-data
        persistentVolumeClaim:
          claimName: mycat-pvc
      - name: mycat-rule-xml
        configMap:
          name: mycat-configmap
          items:
          - key: rule.xml
            path: rule.xml
      - name: mycat-schema-xml
        configMap:
          name: mycat-configmap
          items:
          - key: schema.xml
            path: schema.xml
      - name: mycat-server-xml
        configMap:
          name: mycat-configmap
          items:
          - key: server.xml
            path: server.xml
      imagePullSecrets:
      - name: regcred