apiVersion: v1
kind: Service
metadata:
  name: mycat-service
  namespace: test-namespace
  labels:
    app: mycat-service
spec:
  ports:
  - name: mycat
    port: 5432
    targetPort: 8066
  - name: mycat-admin
    port: 9066
  selector:
    app: mycat