apiVersion: v1
kind: Service
metadata:
  name: mycat-service
  namespace: test-namespace
  labels:
    app: mycat-service
spec:
  ports:
  - port: 8066
    name: mycat
  - port: 9066
    name: mycat-admin
  selector:
    app: mycat