apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfrog-pvc
  namespace: test-namespace
  annotations:
    volume.beta.kubernetes.io/storage-class: "my-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi