apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jfrog-pvc
  namespace: test-namespace
spec:
  storageClassName: my-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi