kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonatype-nexus
  namespace: test-namespace
spec:
  storageClassName: my-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi