apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-computing-deployment
  namespace: test-namespace
  labels:
    app: loan-computing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-computing
  template:
    metadata:
      labels:
        app: loan-computing
    spec:
      containers:
      - name: loan-computing
        image: hub.cathay/kafka-topic-data-loader:latest
      volumeMounts:
        - mountPath: /config
          name: loan-computing-data
    volumes:
    - name: loan-computing-data
      persistentVolumeClaim:
        claimName: loan-computing-pvc
    nodeSelector:
      nodetype: worker