apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader-deployment
  namespace: test-namespace
  labels:
    app: data-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      containers:
      - name: data-loader
        image: hub.cathay/kafka-topic-data-loader:latest
        volumeMounts:
        - mountPath: /config
          name: data-loader-data
          subPath: data-loader
      volumes:
      - name: data-loader-data
        persistentVolumeClaim:
          claimName: loan-computing-pvc
      nodeSelector:
        nodetype: worker