apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  labels:
    type: gitea-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /root/data/gitea
  nodeAffinity:
    nodeSelector:
      data-storage: "true"