apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
  labels:
    type: gitea-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /root/data/gitea
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: data-storage
          operator: In
          values:
          - true