apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    type: registry-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /root/data/registry
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: data-storage
          operator: In
          values:
          - true