apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: test-namespace
  labels:
    app: mysql
data:
  MYSQL_ROOT_PASSWORD: cathaylife
  MYSQL_DATABASE: mycat
  MYSQL_USER: mycat
  MYSQL_PASSWORD: cathaylife
  MYSQL_PORT: "5432"