apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: test-namespace
  labels:
    app: mysql
data:
  MYSQL_DATABASE: DBAB
  MYSQL_ROOT_PASSWORD: cathaylife
  MYSQL_USER: dbab
  MYSQL_PASSWORD: dbab