---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test-namespace
  name: jenkins-role
rules:
- apiGroups: ["", "extensions", "apps", "autoscaling"]
  resources: ["ingresses","services","deployments", "pods", "horizontalpodautoscalers"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["ingresses/exec","services/exec","deployments/exec", "pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["ingresses/log","services/log","deployments/log", "pods/log"]
  verbs: ["delete","get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role
subjects:
- kind: ServiceAccount
  name: jenkins-sa